nome = str(input('Nome: ')).strip()
print('Analisando...')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras, sem espaços'.format(len(nome) - nome.count(' ')))
separa = nome.split()
print('Seu primeiro nome tem {}'.format(separa [0], len(separa[0])))
