n = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(n))
print('É um número? ', n.isnumeric())
print('Só tem espaço? ', n.isspace())
print('É alfanumérico? ', n.isalnum())
print('Está em maiuscúlas? ', n.isupper())
print('Está em minuscúlas? ', n.islower())
print('Está capitalizada? ', n.istitle())
print('É alfabética? ', n.isalpha())