T = int(input('Digite um número:'))
print('A tabuada do número {} é: '.format(T))
print('{} x {} = {}'.format(T, 1, (T*1)))
print('{} x {} = {}'.format(T, 2, (T*2)))
print('{} x {} = {}'.format(T, 3, (T*3)))
print('{} x {} = {}'.format(T, 4, (T*4)))
print('{} x {} = {}'.format(T, 5, (T*5)))
print('{} x {} = {}'.format(T, 6, (T*6)))
print('{} x {} = {}'.format(T, 7, (T*7)))
print('{} x {} = {}'.format(T, 8, (T*8)))
print('{} x {} = {}'.format(T, 9, (T*9)))
print('{} x {} = {}'.format(T, 10, (T*10)))

